# Generated by Django 3.2 on 2021-05-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.ownercar', verbose_name="Owners' car"),
        ),
        migrations.AlterField(
            model_name='ownercar',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car', verbose_name='Car'),
        ),
    ]
