# Generated by Django 3.2 on 2021-05-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_orderline_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='autoservice.service', verbose_name='Service'),
        ),
    ]
