# Generated by Django 3.2 on 2021-05-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_orderline_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled')], default='draft', help_text='Status', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service', verbose_name='Service'),
        ),
    ]
