# Generated by Django 3.2 on 2021-05-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_auto_20210505_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercar',
            name='picture',
            field=models.ImageField(null=True, upload_to='cars', verbose_name='Car photo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.ownercar', verbose_name="Clients' car"),
        ),
    ]
