# Generated by Django 3.2 on 2021-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_auto_20210510_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
