# Generated by Django 3.2 on 2021-05-12 13:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_alter_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercar',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
