# Generated by Django 3.2 on 2021-05-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_orderreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='Cost'),
        ),
    ]
