# Generated by Django 3.2 on 2021-05-13 09:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0011_orderline_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='ownercar',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownercar',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cars', verbose_name='Car photo'),
        ),
    ]
