# Generated by Django 3.2 on 2021-05-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0012_auto_20210513_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='cost',
        ),
        migrations.AlterField(
            model_name='ownercar',
            name='picture',
            field=models.ImageField(null=True, upload_to='cars', verbose_name='Car photo'),
        ),
    ]
